DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  ID           BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FirstName    VARCHAR(40) NOT NULL,
	LastName     VARCHAR(40) NOT NULL,
	Email        VARCHAR(40) NOT NULL,
	PasswordHash VARCHAR(80) NOT NULL
);
