DROP TABLE IF EXISTS plan_participant_users;

CREATE TABLE IF NOT EXISTS plan_participant_users (
  ID     BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UserId BIGINT(20) UNSIGNED NOT NULL,
	PlanId BIGINT(20) UNSIGNED NOT NULL
);
